export function hexToRgb(hex: string) {
  const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);
  return `${r},${g},${b}`;
}

const NODES_FR = [
  {id:9,color:'#B8962E',freq:963,role:"L'attractor universel — le Qi absolu",quote:"Si tu connaissais la magnificence du 3, 6 et 9..."},
  {id:1,color:'#C87941',freq:174,role:"Yang naissant — le premier souffle du Qi",quote:"Le Un engendre le Deux"},
  {id:2,color:'#5B4BC0',freq:285,role:"Yang en expansion — le Qi se déploie",quote:"Le mouvement est la vie du Qi"},
  {id:3,color:'#C9A84C',freq:396,role:"Axe cosmique — principe créateur",quote:"Le Trois engendre les dix mille êtres"},
  {id:4,color:'#3C6090',freq:417,role:"Yang mature — le Qi stabilisé",quote:"Quatre directions de l'espace, quatre saisons"},
  {id:5,color:'#A0406A',freq:528,role:"Pivot Yin-Yang — le centre, la charnière",quote:"Les cinq éléments — Bois, Feu, Terre, Métal, Eau"},
  {id:6,color:'#0D7A6B',freq:639,role:"Axe cosmique — harmonie Yin-Yang accomplie",quote:"Six lignes du I Ching"},
  {id:7,color:'#8B3018',freq:741,role:"Yin en retour — l'énergie se régénère",quote:"Sept planètes, sept notes, sept chakras"},
  {id:8,color:'#4A2D8A',freq:852,role:"Yin profond — concentré, prêt à rebondir",quote:"Huit trigrammes du Ba Gua"},
];

const NODES_EN = [
  {id:9,color:'#B8962E',freq:963,role:"The universal attractor — absolute Qi",quote:"If you only knew the magnificence of the 3, 6 and 9..."},
  {id:1,color:'#C87941',freq:174,role:"Nascent Yang — the first breath of Qi",quote:"The One begets the Two"},
  {id:2,color:'#5B4BC0',freq:285,role:"Expanding Yang — Qi unfolds",quote:"Movement is the life of Qi"},
  {id:3,color:'#C9A84C',freq:396,role:"Cosmic axis — creative principle",quote:"The Three begets the ten thousand things"},
  {id:4,color:'#3C6090',freq:417,role:"Mature Yang — stabilized Qi",quote:"Four directions of space, four seasons"},
  {id:5,color:'#A0406A',freq:528,role:"Yin-Yang pivot — the center, the hinge",quote:"The five elements — Wood, Fire, Earth, Metal, Water"},
  {id:6,color:'#0D7A6B',freq:639,role:"Cosmic axis — Yin-Yang harmony achieved",quote:"Six lines of the I Ching"},
  {id:7,color:'#8B3018',freq:741,role:"Returning Yin — energy regenerates",quote:"Seven planets, seven notes, seven chakras"},
  {id:8,color:'#4A2D8A',freq:852,role:"Deep Yin — concentrated, ready to rebound",quote:"Eight trigrams of the Ba Gua"},
];

const FREQS_FR = [
  {number:1,freq:174,name:"Fondation · Anesthésique",color:'#C87941',reduction:'1+7+4=12→3',
   desc:"La plus basse fréquence solfège. Soulagement douleur physique, relaxation musculaire, sécurité.",
   benefits:['douleurs dos/jambes','relaxation musculaire','réduction stress','qualité sommeil'],
   comp:{freq:285,name:"Régénération cellulaire",reduction:"2+8+5=15→6",desc:"Signal de reconstruction. Régénération tissulaire, immunité."},
   gates:[{t:"Méditation matin",d:"5–20min"},{t:"Douleur physique",d:"20–30min"},{t:"Sommeil profond",d:"toute la nuit"}]},
  {number:2,freq:285,name:"Régénération · Immunité",color:'#5B4BC0',reduction:'2+8+5=15→6',
   desc:"Stimule la régénération cellulaire et l'immunité. Fréquence des tissus en réparation.",
   benefits:['régénération tissulaire','guérison blessures','immunité renforcée','équilibre émotionnel'],
   comp:{freq:417,name:"Transformation · Changement",reduction:"4+1+7=12→3",desc:"Nettoie les croyances limitantes, efface les schémas négatifs."},
   gates:[{t:"Guérison physique",d:"15–30min"},{t:"Libérer le passé",d:"20min"},{t:"Créativité",d:"30min"}]},
  {number:3,freq:396,name:"Libération culpabilité",color:'#C9A84C',reduction:'3+9+6=18→9',
   desc:"Dissout la culpabilité et la peur qui bloquent le Qi. Première des 6 fréquences solfège.",
   benefits:['libération culpabilité','dissolution peur','reconnexion Qi','ancrage'],
   comp:{freq:528,name:"ADN · Amour · Miracle",reduction:"5+2+8=15→6",desc:"Fréquence de l'amour. Réparation ADN. Réduction stress en 5 min."},
   gates:[{t:"Méditation libération",d:"20min"},{t:"Guérison cellulaire",d:"15–30min"},{t:"Séquence 396→528",d:"40min"}]},
  {number:4,freq:417,name:"Transformation · Changement",color:'#3C6090',reduction:'4+1+7=12→3',
   desc:"Nettoie les croyances limitantes. Facilite le changement, efface les traumatismes passés.",
   benefits:['dissolution traumatismes','changement schémas','nettoyage espace','ouverture'],
   comp:{freq:639,name:"Connexion · Relations",reduction:"6+3+9=18→9",desc:"Harmonie dans les relations. Connexion au champ collectif."},
   gates:[{t:"Nettoyage espace",d:"30min"},{t:"Méditation cœur",d:"20min"},{t:"Avant conversation",d:"10min"}]},
  {number:5,freq:528,name:"ADN · Miracle · Amour",color:'#A0406A',reduction:'5+2+8=15→6',
   desc:"Au cœur du mouvement. Fréquence de transformation, cohérence cellulaire, réparation ADN.",
   benefits:['réparation cellulaire','clarté intérieure','amour inconditionnel','transformation'],
   comp:{freq:741,name:"Expression · Détox",reduction:"7+4+1=12→3",desc:"Nettoie l'espace émotionnel. Expression authentique. Protection EM."},
   gates:[{t:"Détox digitale",d:"20–30min"},{t:"Expression créatrice",d:"10min avant"},{t:"Guérison cellulaire",d:"30min"}]},
  {number:6,freq:639,name:"Connexion · Harmonie",color:'#0D7A6B',reduction:'6+3+9=18→9',
   desc:"Fréquence du 6. Harmonie dans les relations. Connexion au champ collectif (Projet Princeton).",
   benefits:['harmonisation relations','amour empathie','communication','champ collectif'],
   comp:{freq:852,name:"Intuition · Ordre spirituel",reduction:"8+5+2=15→6",desc:"L'ordre spirituel retrouvé. La conscience s'éveille."},
   gates:[{t:"Méditation sociale",d:"15min"},{t:"Activation 3e œil",d:"30min"},{t:"Feng Shui sonore",d:"en continu"}]},
  {number:7,freq:741,name:"Expression · Détox · Purif.",color:'#8B3018',reduction:'7+4+1=12→3',
   desc:"Nettoie l'espace émotionnel et physique. Expression authentique. Protection électromagnétique.",
   benefits:['nettoyage toxines','expression libérée','résolution créative','protection EM'],
   comp:{freq:852,name:"Intuition · Retour ordre",reduction:"8+5+2=15→6",desc:"L'ordre spirituel retrouvé. La conscience s'éveille."},
   gates:[{t:"Detox EM",d:"20–30min"},{t:"Libérer la parole",d:"10min avant"},{t:"Purification espace",d:"30min"}]},
  {number:8,freq:852,name:"Retour ordre spirituel",color:'#4A2D8A',reduction:'8+5+2=15→6',
   desc:"L'ordre spirituel retrouvé. La conscience s'éveille avant la transcendance finale du 9.",
   benefits:['ordre spirituel','intuition renforcée','connexion soi supérieur','états profonds'],
   comp:{freq:963,name:"Conscience divine · Éveil",reduction:"9+6+3=18→9",desc:"Active la glande pinéale. Connecte au champ global."},
   gates:[{t:"Méditation avancée",d:"45min"},{t:"Activation pinéale",d:"20min"},{t:"Transition sommeil",d:"30min"}]},
  {number:9,freq:963,name:"Conscience divine · Couronne",color:'#B8962E',reduction:'9+6+3=18→9',
   desc:"Se réduit à elle-même comme le 9. Active la glande pinéale. Connecte au champ global.",
   benefits:['activation pinéale','conscience universelle','états de plénitude','éveil spirituel'],
   comp:{freq:432,name:"Accord Terre · Schumann",reduction:"4+3+2=9",desc:"Le La naturel. Schumann 7,83Hz→18→9. Résonance planétaire."},
   gates:[{t:"Union cosmique",d:"30–60min"},{t:"Accord 432Hz",d:"en continu"},{t:"Cycle complet",d:"90min"}]},
];

const FREQS_EN = [
  {number:1,freq:174,name:"Foundation · Anesthetic",color:'#C87941',reduction:'1+7+4=12→3',
   desc:"The lowest solfeggio frequency. Physical pain relief, muscle relaxation, sense of safety.",
   benefits:['back/leg pain','muscle relaxation','stress reduction','sleep quality'],
   comp:{freq:285,name:"Cellular Regeneration",reduction:"2+8+5=15→6",desc:"Reconstruction signal. Tissue regeneration, immunity."},
   gates:[{t:"Morning meditation",d:"5–20min"},{t:"Physical pain",d:"20–30min"},{t:"Deep sleep",d:"all night"}]},
  {number:2,freq:285,name:"Regeneration · Immunity",color:'#5B4BC0',reduction:'2+8+5=15→6',
   desc:"Stimulates cellular regeneration and immunity. Frequency of tissues in repair.",
   benefits:['tissue regeneration','wound healing','boosted immunity','emotional balance'],
   comp:{freq:417,name:"Transformation · Change",reduction:"4+1+7=12→3",desc:"Clears limiting beliefs, erases negative patterns."},
   gates:[{t:"Physical healing",d:"15–30min"},{t:"Releasing the past",d:"20min"},{t:"Creativity",d:"30min"}]},
  {number:3,freq:396,name:"Liberation from Guilt",color:'#C9A84C',reduction:'3+9+6=18→9',
   desc:"Dissolves guilt and fear that block Qi. First of the 6 fundamental solfeggio frequencies.",
   benefits:['liberation from guilt','dissolving fear','reconnecting Qi','grounding'],
   comp:{freq:528,name:"DNA · Love · Miracle",reduction:"5+2+8=15→6",desc:"Frequency of love. DNA repair. Stress reduction in 5 min."},
   gates:[{t:"Liberation meditat.",d:"20min"},{t:"Cellular healing",d:"15–30min"},{t:"Sequence 396→528",d:"40min"}]},
  {number:4,freq:417,name:"Transformation · Change",color:'#3C6090',reduction:'4+1+7=12→3',
   desc:"Clears limiting beliefs. Facilitates change, erases past traumas.",
   benefits:['dissolving traumas','changing patterns','space clearing','opening up'],
   comp:{freq:639,name:"Connection · Relationships",reduction:"6+3+9=18→9",desc:"Harmony in relationships. Connection to the collective field."},
   gates:[{t:"Space clearing",d:"30min"},{t:"Heart meditation",d:"20min"},{t:"Before conversation",d:"10min"}]},
  {number:5,freq:528,name:"DNA · Miracle · Love",color:'#A0406A',reduction:'5+2+8=15→6',
   desc:"At the heart of the movement. Transformation frequency, cellular coherence, DNA repair.",
   benefits:['cellular repair','inner clarity','unconditional love','transformation'],
   comp:{freq:741,name:"Expression · Detox",reduction:"7+4+1=12→3",desc:"Clears emotional space. Authentic expression. EMF protection."},
   gates:[{t:"Digital detox",d:"20–30min"},{t:"Creative expression",d:"10min before"},{t:"Cellular healing",d:"30min"}]},
  {number:6,freq:639,name:"Connection · Harmony",color:'#0D7A6B',reduction:'6+3+9=18→9',
   desc:"Frequency of the 6. Harmony in relationships. Connection to the collective field.",
   benefits:['relationship harmony','love and empathy','communication','collective field'],
   comp:{freq:852,name:"Intuition · Spiritual Order",reduction:"8+5+2=15→6",desc:"Spiritual order restored. Consciousness awakens."},
   gates:[{t:"Social meditation",d:"15min"},{t:"3rd eye activation",d:"30min"},{t:"Sonic Feng Shui",d:"continuous"}]},
  {number:7,freq:741,name:"Expression · Detox · Purif.",color:'#8B3018',reduction:'7+4+1=12→3',
   desc:"Clears emotional and physical space. Authentic expression. EMF protection.",
   benefits:['toxin clearing','freed expression','creative resolution','EMF protection'],
   comp:{freq:852,name:"Intuition · Return to Order",reduction:"8+5+2=15→6",desc:"Spiritual order restored. Consciousness awakens."},
   gates:[{t:"EMF Detox",d:"20–30min"},{t:"Freeing speech",d:"10min before"},{t:"Space purification",d:"30min"}]},
  {number:8,freq:852,name:"Return to Spiritual Order",color:'#4A2D8A',reduction:'8+5+2=15→6',
   desc:"Spiritual order restored. Consciousness awakens before the final transcendence of the 9.",
   benefits:['spiritual order','heightened intuition','higher self connection','deep states'],
   comp:{freq:963,name:"Divine Consc. · Awakening",reduction:"9+6+3=18→9",desc:"Activates the pineal gland. Connects to the global field."},
   gates:[{t:"Adv. meditation",d:"45min"},{t:"Pineal activation",d:"20min"},{t:"Sleep transition",d:"30min"}]},
  {number:9,freq:963,name:"Divine Consc. · Crown",color:'#B8962E',reduction:'9+6+3=18→9',
   desc:"Reduces to itself like the 9. Activates the pineal gland. Connects to the global field.",
   benefits:['pineal activation','universal conscious.','states of wholeness','spiritual awakening'],
   comp:{freq:432,name:"Earth Harm. · Schumann",reduction:"4+3+2=9",desc:"The natural A. Schumann 7.83Hz→18→9. Planetary resonance."},
   gates:[{t:"Cosmic union",d:"30–60min"},{t:"432Hz tuning",d:"continuous"},{t:"Full cycle",d:"90min"}]},
];

const FOL_FREQS_FR = [
  ...FREQS_FR.map(f=>({hz:f.freq,name:f.name,rgb:hexToRgb(f.color),desc:f.desc})),
  {hz:432,name:"L'Univers · Schumann",rgb:null,desc:"432 Hz — la fréquence de résonance de l'univers. Le La naturel. Le corps humain comme antenne terrestre."},
];

const FOL_FREQS_EN = [
  ...FREQS_EN.map(f=>({hz:f.freq,name:f.name,rgb:hexToRgb(f.color),desc:f.desc})),
  {hz:432,name:"The Universe · Schumann",rgb:null,desc:"432 Hz — the resonance frequency of the universe. The natural A. The human body as a terrestrial antenna."},
];

export const I18N: Record<string, any> = {
  fr: {
    nodes: NODES_FR, freqs: FREQS_FR, folFreqs: FOL_FREQS_FR,
    tabs:['Vortex','Réduction','Yin · Yang','Fréquences','Pont Est-Ouest','Résonance','Fleur de Vie'],
    username:'Nom du voyageur',login:'Connexion',guest:'Continuer en invité',duelMode:'Mode duel (IA)',
    animateFlow:'Animer le flux',pauseFlow:'Pause flux',selectNode:'Cliquez un nombre sur le vortex',
    cosmicRole:'Rôle cosmique',frequency:'Fréquence',resonance:'Résonance',stability:'Stabilité',
    leftPolarity:'Polarité gauche',rightPolarity:'Polarité droite',balance:'Équilibrez 6 et 3',
    raiseEnergy:'Élevez l\'énergie vers 9',gateOpen:'LA PORTE S\'OUVRE',victory:'Victoire',
    defeat:'Défaite',draw:'Égalité',player:'Joueur',opponent:'Adversaire IA',reset:'Réinitialiser',
    loop:'Boucle',session:'Session',min:'min',fileMissing:'Placez le fichier :',
    benefits:'Bénéfices',gates:'Portes pratiques',primary:'Fréquence principale',
    complementary:'Fréquence complémentaire',tryNumber:'Essayez un nombre',reduce:'Réduire',
    ruleOf9:'La règle du 9',multiples:'Table des multiples',result:'Résultat',digitSum:'Somme',
    reduced:'Réduit',pattern:'Motif',yangSeq:'Séquence Yang · Expansion · Lumière',
    yinSeq:'Séquence Yin · Contraction · Ombre',sacredPairs:'Les paires sacrées',
    never369:'3, 6 et 9 n\'apparaissent jamais dans les séquences de doublement.',
    chineseTrad:'Tradition chinoise',vortexTesla:'Vortex Math · Tesla',modernPhysics:'Physique moderne',
    concrete:'Manifestations concrètes',kirlian:'L\'effet Kirlian',axisCosmic:'Axe cosmique',fluxYang:'Flux Yang',
    cancel:'Annuler',save:'Sauvegarder',profile:'Profil',solfeggioSeries:'Série Solfège',freqActive:'Fréquence Active',
    anchorEarth:"S'ancrer à la Terre",subtitle:"L'Énergie Secrète de l'Univers · Google I/O 2026",
    teslaQuote:"\"Si vous voulez trouver les secrets de l'univers, pensez en termes d'énergie, de fréquence et de vibration.\" — Nikola Tesla",
    ruleOf9Desc: "Chaque multiple de 9 se réduit toujours à 9. L'éternel constant.",
    never369Desc: "Ils existent sur un axe séparé — l'axe cosmique que Tesla a nommé la clé de l'univers. Leur somme deux à deux revient toujours à 9 : l'unité retrouvée.",
    yyQuote: '"Au fil du jour, la montagne a toujours un versant dans l\'ombre et un autre baigné de lumière."',
    ewAuthor: "Maxence Layet — L'Énergie Secrète de l'Univers",
    ewIntro: "Dans la vision symbolique du vortex, chaque nombre vibre avec les forces du Qi. Tesla réinvente les principes orientaux millénaires à l'aune de l'électromagnétisme moderne.",
    kirlianDesc: "La <em>photographie Kirlian</em> révèle le champ vibratoire des êtres vivants. Une feuille fraîchement coupée affiche un halo lumineux, qui s'estompe à mesure que le <strong>Qi</strong> s'épuise. Tesla parlait d'<strong>Énergie Radiante</strong>, une force invisible imprégnant l'univers, connectant matière et conscience.",
    ewItems: [
      ['Qi (énergie vitale universelle)','Méridiens d\'acupuncture','Yin · Yang (dualité cyclique)','Feng Shui (flux géomantiques)','Qi Gong (maîtrise du souffle)','Mémoire de l\'eau','3 · 6 · 9 (nombres sacrés)','Le Tao — la Voie universelle'],
      ['Séquence 1-2-4-8-7-5 + axe 3-6-9','Champ torique (géométrie du tore)','Flux Yang / Yin du cercle','Zones de cohérence du tore','Réduction numérique (digital root)','Auto-similarité du 9','Axe cosmique 3-6-9','Infini (∞) au centre du vortex'],
      ['Champ électromagnétique biologique','Conductivité électrodermale','Dualité onde/corpuscule','Cohérence quantique','Biofeedback · neurofeedback','Mémoire de l\'eau (Benveniste)','Fréquences thérapeutiques (Hz)','Projet Conscience Globale Princeton'],
      ['Photothérapie lumière rouge (660nm→3)','Magnétothérapie (os, fractures)','Électropuncture (acupuncture)','Ondes gamma moines tibétains 40Hz→4','Photographie Kirlian (aura visible)','Électroculture (champs agricoles)','Interface cerveau-ordinateur','Schumann 7,83Hz→18→9']
    ],
    resKbd: 'Clavier: 1–9 · Space pulse · R reset',
    share: 'Partager',
    digit9: '⟲ 9',
    digitAxis: '◈ axe',
    digitFlux: '● flux',
    ttLang: "Changer la langue",
    ttProfile: "Modifier le profil",
    ttVortexCanvas: "Cliquez sur un nœud pour voir ses détails cosmiques",
    ttAnimate: "Basculer l'animation du flux",
    ttTri: "Afficher/Masquer l'axe 3-6-9",
    ttAmber: "Afficher/Masquer le triangle 1-4-7",
    ttIndigo: "Afficher/Masquer le triangle 2-5-8",
    ttPath: "Afficher/Masquer le flux Yin-Yang",
    ttShare: "Partager l'image du vortex",
    ttReduce: "Calculer la racine numérique",
    ttNumInput: "Entrez un nombre à réduire",
    ttMult: "Calculer les multiples de ce nombre",
    ttFreqTab: "Sélectionner cette fréquence",
    ttPlayPause: "Lecture / Pause",
    ttVol: "Ajuster le volume",
    ttLoop: "Basculer la lecture en boucle",
    ttTimer: "Lancer le minuteur de session",
    ttResCanvas: "Cliquez sur les nœuds pour les activer",
    ttReset: "Réinitialiser la résonance",
    ttFolDd: "Sélectionner une fréquence",
    ttFol369: "Afficher/Masquer les axes 369",
    ttFolInfo: "Afficher/Masquer les informations",
    ttFolWave: "Changer la forme d'onde",
    resIntro: "Équilibrez les pôles gauche (3) et droit (6) du vortex. Lorsque l'équilibre est parfait, utilisez le 9 pour élever la résonance jusqu'à ouvrir la porte. Mais attention, la stabilité se dégrade avec le temps et l'usage asymétrique de l'énergie. Les autres nombres apportent de faibles altérations.",
    tuningForkVideo: "Vidéo son du diapason",
    folHowToTitle: "Comment utiliser le Fréquenceur",
    folHowToContent: "Touchez ou glissez à l'intérieur de la géométrie pour moduler la résonance. Le centre émet la fréquence pure (panoramique centré). Éloignez-vous du centre pour modifier l'amplitude et la phase. Modifiez la forme d'onde (sine, triangle, square) pour explorer d'autres textures vibratoires.",
    tuningFork: "Diapason",
    tapToPlay: "Toucher pour écouter"
  },
  en: {
    nodes: NODES_EN, freqs: FREQS_EN, folFreqs: FOL_FREQS_EN,
    tabs:['Vortex','Reduction','Yin · Yang','Frequencies','East-West Bridge','Resonance','Flower of Life'],
    username:'Traveller name',login:'Login',guest:'Continue as guest',duelMode:'Duel mode (AI)',
    animateFlow:'Animate flow',pauseFlow:'Pause flow',selectNode:'Click a number on the vortex',
    cosmicRole:'Cosmic role',frequency:'Frequency',resonance:'Resonance',stability:'Stability',
    leftPolarity:'Left polarity',rightPolarity:'Right polarity',balance:'Balance 6 and 3',
    raiseEnergy:'Raise energy toward 9',gateOpen:'THE GATE OPENS',victory:'Victory',
    defeat:'Defeat',draw:'Draw',player:'Player',opponent:'AI Opponent',reset:'Reset',
    loop:'Loop',session:'Session',min:'min',fileMissing:'Place the file:',
    benefits:'Benefits',gates:'Practical gates',primary:'Primary frequency',
    complementary:'Complementary frequency',tryNumber:'Try any number',reduce:'Reduce',
    ruleOf9:'The rule of 9',multiples:'Multiples table',result:'Result',digitSum:'Digit sum',
    reduced:'Reduced',pattern:'Pattern',yangSeq:'Yang Sequence · Expansion · Light',
    yinSeq:'Yin Sequence · Contraction · Shadow',sacredPairs:'The sacred pairs',
    never369:'3, 6 and 9 never appear in the doubling sequences.',
    chineseTrad:'Chinese tradition',vortexTesla:'Vortex Math · Tesla',modernPhysics:'Modern physics',
    concrete:'Concrete manifestations',kirlian:'The Kirlian effect',axisCosmic:'Cosmic axis',fluxYang:'Yang flow',
    cancel:'Cancel',save:'Save',profile:'Profile',solfeggioSeries:'Solfeggio Series',freqActive:'Active Frequency',
    anchorEarth:'Ground to Earth',subtitle:'The Secret Energy of the Universe · Google I/O 2026',
    teslaQuote:'"If you want to find the secrets of the universe, think in terms of energy, frequency and vibration." — Nikola Tesla',
    ruleOf9Desc: "Every multiple of 9 always reduces back to 9. The eternal constant.",
    never369Desc: "They exist on a separate axis — the cosmic axis that Tesla named the key to the universe. Their sum in pairs always returns to 9: unity restored.",
    yyQuote: '"Throughout the day, the mountain always has one side in shadow and another bathed in light."',
    ewAuthor: "Maxence Layet — The Secret Energy of the Universe",
    ewIntro: "In the symbolic vision of the vortex, each number vibrates with the forces of Qi. Tesla reinvents millennial Eastern principles through the lens of modern electromagnetism.",
    kirlianDesc: "<em>Kirlian photography</em> reveals the vibratory field of living beings. A freshly cut leaf displays a luminous halo, which fades as the <strong>Qi</strong> is depleted. Tesla spoke of <strong>Radiant Energy</strong>, an invisible force permeating the universe, connecting matter and consciousness.",
    ewItems: [
      ['Qi (universal vital energy)','Acupuncture meridians','Yin · Yang (cyclic duality)','Feng Shui (geomantic flows)','Qi Gong (breath mastery)','Memory of water','3 · 6 · 9 (sacred numbers)','The Tao — the universal Way'],
      ['Sequence 1-2-4-8-7-5 + axis 3-6-9','Toroidal field (torus geometry)','Yang / Yin flow of the circle','Torus coherence zones','Digital root','Self-similarity of the 9','Cosmic axis 3-6-9','Infinity (∞) at vortex center'],
      ['Biological electromagnetic field','Electrodermal conductivity','Wave/particle duality','Quantum coherence','Biofeedback · neurofeedback','Memory of water (Benveniste)','Therapeutic frequencies (Hz)','Princeton Global Consciousness Project'],
      ['Red light therapy (660nm→3)','Magnetotherapy (bones, fractures)','Electropuncture (acupuncture)','Tibetan monks gamma waves 40Hz→4','Kirlian photography (visible aura)','Electroculture (agricultural fields)','Brain-computer interface','Schumann 7.83Hz→18→9']
    ],
    resKbd: 'Keyboard: 1–9 · Space pulse · R reset',
    share: 'Share',
    digit9: '⟲ 9',
    digitAxis: '◈ axis',
    digitFlux: '● flux',
    ttLang: "Change language",
    ttProfile: "Edit profile",
    ttVortexCanvas: "Click a node to see its cosmic details",
    ttAnimate: "Toggle flow animation",
    ttTri: "Toggle 3-6-9 axis",
    ttAmber: "Toggle 1-4-7 triangle",
    ttIndigo: "Toggle 2-5-8 triangle",
    ttPath: "Toggle Yin-Yang flux",
    ttShare: "Share vortex image",
    ttReduce: "Calculate digital root",
    ttNumInput: "Enter a number to reduce",
    ttMult: "Calculate multiples for this number",
    ttFreqTab: "Select this frequency",
    ttPlayPause: "Play / Pause",
    ttVol: "Adjust volume",
    ttLoop: "Toggle loop",
    ttTimer: "Start session timer",
    ttResCanvas: "Click nodes to activate them",
    ttReset: "Reset resonance",
    ttFolDd: "Select frequency",
    ttFol369: "Toggle 369 axes",
    ttFolInfo: "Toggle info",
    ttFolWave: "Change waveform",
    resIntro: "Balance the left (3) and right (6) poles of the vortex. Once perfect balance is achieved, use the 9 to raise resonance until the gate opens. But beware, stability degrades over time and with asymmetrical energy usage. Other numbers provide minor alterations.",
    tuningForkVideo: "Tuning fork sound video",
    folHowToTitle: "How to use the Frequencer",
    folHowToContent: "Touch or drag inside the geometry to modulate resonance. The center emits pure frequency (centered panning). Move outward to alter amplitude and spatial phase. Change the waveform (sine, triangle, square) to explore different vibrational textures.",
    tuningFork: "Tuning Fork",
    tapToPlay: "Tap to play"
  },
  es: {
    nodes: NODES_EN,
    freqs: FREQS_EN,
    folFreqs: FOL_FREQS_EN,
    tabs:['Vórtice','Reducción','Yin · Yang','Frecuencias','Puente Este-Oeste','Resonancia','Flor de la Vida'],
    username:'Nombre del viajero',login:'Iniciar',guest:'Continuar como invitado',duelMode:'Modo duelo (IA)',
    animateFlow:'Animar flujo',pauseFlow:'Pausar flujo',selectNode:'Haz clic en un número del vórtice',
    cosmicRole:'Rol cósmico',frequency:'Frecuencia',resonance:'Resonancia',stability:'Estabilidad',
    leftPolarity:'Polaridad izquierda',rightPolarity:'Polaridad derecha',balance:'Equilibra 6 y 3',
    raiseEnergy:'Eleva la energía hacia el 9',gateOpen:'LA PUERTA SE ABRE',victory:'Victoria',
    defeat:'Derrota',draw:'Empate',player:'Jugador',opponent:'Oponente IA',reset:'Reiniciar',
    loop:'Bucle',session:'Sesión',min:'min',fileMissing:'Falta el archivo:',
    benefits:'Beneficios',gates:'Puertas prácticas',primary:'Frecuencia principal',
    complementary:'Frecuencia complementaria',tryNumber:'Prueba un número',reduce:'Reducir',
    ruleOf9:'La regla del 9',multiples:'Tabla de múltiplos',result:'Resultado',digitSum:'Suma de dígitos',
    reduced:'Reducido',pattern:'Patrón',yangSeq:'Secuencia Yang · Expansión · Luz',
    yinSeq:'Secuencia Yin · Contracción · Sombra',sacredPairs:'Los pares sagrados',
    never369:'3, 6 y 9 nunca aparecen en las secuencias de duplicación.',
    chineseTrad:'Tradición china',vortexTesla:'Matemática Vórtice · Tesla',modernPhysics:'Física moderna',
    concrete:'Manifestaciones concretas',kirlian:'El efecto Kirlian',axisCosmic:'Eje cósmico',fluxYang:'Flujo Yang',
    cancel:'Cancelar',save:'Guardar',profile:'Perfil',solfeggioSeries:'Serie Solfeggio',freqActive:'Frecuencia Activa',
    anchorEarth:'Anclarse a la Tierra',subtitle:'La Energía Secreta del Universo · Google I/O 2026',
    teslaQuote:'"Si quieres encontrar los secretos del universo, piensa en términos de energía, frecuencia y vibración." — Nikola Tesla',
    ruleOf9Desc: "Cada múltiplo de 9 siempre se reduce a 9. La constante eterna.",
    never369Desc: "Existen en un eje separado: el eje cósmico que Tesla llamó la clave del universo. Su suma en pares siempre devuelve el 9: la unidad restaurada.",
    yyQuote: '"Durante el día, la montaña siempre tiene un lado en la sombra y otro bañado por la luz."',
    ewAuthor: "Maxence Layet — La Energía Secreta del Universo",
    ewIntro: "En la visión simbólica del vórtice, cada número vibra con las fuerzas del Qi. Tesla reinventa milenarios principios orientales bajo la lupa del electromagnetismo moderno.",
    kirlianDesc: "La <em>fotografía Kirlian</em> revela el campo vibratorio de los seres vivos. Una hoja recién cortada muestra un halo luminoso que se desvanece a medida que el <strong>Qi</strong> se agota. Tesla hablaba de la <strong>Energía Radiante</strong>, una fuerza invisible que impregna el universo, conectando materia y conciencia.",
    ewItems: [
      ['Qi (energía vital universal)','Meridianos de acupuntura','Yin · Yang (dualidad cíclica)','Feng Shui (flujos geománticos)','Qi Gong (dominio del aliento)','Memoria del agua','3 · 6 · 9 (números sagrados)','El Tao — el Camino universal'],
      ['Secuencia 1-2-4-8-7-5 + eje 3-6-9','Campo toroidal (geometría del toro)','Flujo Yang / Yin del círculo','Zonas de coherencia del toro','Raíz digital','Autosimilitud del 9','Eje cósmico 3-6-9','Infinito (∞) en el centro del vórtice'],
      ['Campo electromagnético biológico','Conductividad electrodérmica','Dualidad onda/partícula','Coherencia cuántica','Biofeedback · neurofeedback','Memoria del agua (Benveniste)','Frecuencias terapéuticas (Hz)','Proyecto Conciencia Global Princeton'],
      ['Terapia de luz roja (660nm→3)','Magnetoterapia (huesos, fracturas)','Electropuntura (acupuntura)','Ondas gamma monjes tibetanos 40Hz→4','Fotografía Kirlian (aura visible)','Electrocultivo (campos agrícolas)','Interfaz cerebro-computadora','Schumann 7.83Hz→18→9']
    ],
    resKbd: 'Teclado: 1–9 · Espacio: pulso · R: reiniciar',
    share: 'Compartir',
    digit9: '⟲ 9',
    digitAxis: '◈ eje',
    digitFlux: '● flujo',
    ttLang: "Cambiar idioma",
    ttProfile: "Editar perfil",
    ttVortexCanvas: "Haz clic en un nodo para ver sus detalles",
    ttAnimate: "Alternar animación",
    ttTri: "Alternar eje 3-6-9",
    ttAmber: "Alternar triángulo 1-4-7",
    ttIndigo: "Alternar triángulo 2-5-8",
    ttPath: "Alternar flujo Yin-Yang",
    ttShare: "Compartir imagen",
    ttReduce: "Calcular raíz digital",
    ttNumInput: "Ingresar número",
    ttMult: "Calcular múltiplos",
    ttFreqTab: "Seleccionar frecuencia",
    ttPlayPause: "Reproducir / Pausar",
    ttVol: "Ajustar volumen",
    ttLoop: "Alternar bucle",
    ttTimer: "Iniciar temporizador",
    ttResCanvas: "Haz clic en los nodos para activarlos",
    ttReset: "Reiniciar resonancia",
    ttFolDd: "Seleccionar frecuencia",
    ttFol369: "Alternar ejes 369",
    ttFolInfo: "Alternar información",
    ttFolWave: "Cambiar forma de onda",
    resIntro: "Equilibra los polos izquierdo (3) y derecho (6) del vórtice. Una vez logrado el equilibrio, usa el 9 para elevar la resonancia y abrir la puerta. Pero cuidado, la estabilidad se degrada con el tiempo. Otros números proporcionan alteraciones menores.",
    tuningForkVideo: "Video sonido del diapasón",
    folHowToTitle: "Cómo usar el Frecuenciador",
    folHowToContent: "Toca o arrastra dentro de la geometría para modular la resonancia. El centro emite la frecuencia pura. Muévete hacia afuera para alterar la amplitud y la fase. Cambia la forma de onda para explorar distintas texturas.",
    tuningFork: "Diapasón",
    tapToPlay: "Tocar para escuchar"
  },
  de: {
    nodes: NODES_EN,
    freqs: FREQS_EN,
    folFreqs: FOL_FREQS_EN,
    tabs:['Vortex','Reduktion','Yin · Yang','Frequenzen','Ost-West-Brücke','Resonanz','Blume des Lebens'],
    username:'Reisender Name',login:'Anmelden',guest:'Als Gast fortfahren',duelMode:'Duellmodus (KI)',
    animateFlow:'Fluss animieren',pauseFlow:'Fluss pausieren',selectNode:'Klicke eine Zahl an',
    cosmicRole:'Kosmische Rolle',frequency:'Frequenz',resonance:'Resonanz',stability:'Stabilität',
    leftPolarity:'Linke Polarität',rightPolarity:'Rechte Polarität',balance:'Gleiche 6 und 3 aus',
    raiseEnergy:'Energie auf 9 heben',gateOpen:'DAS TOR ÖFFNET SICH',victory:'Sieg',
    defeat:'Niederlage',draw:'Unentschieden',player:'Spieler',opponent:'KI-Gegner',reset:'Zurücksetzen',
    loop:'Schleife',session:'Sitzung',min:'Min',fileMissing:'Fehlende Datei:',
    benefits:'Vorteile',gates:'Praktische Tore',primary:'Hauptfrequenz',
    complementary:'Zusatzfrequenz',tryNumber:'Teste eine Zahl',reduce:'Reduzieren',
    ruleOf9:'Die Regel der 9',multiples:'Vielfachentabelle',result:'Ergebnis',digitSum:'Quersumme',
    reduced:'Reduziert',pattern:'Muster',yangSeq:'Yang-Sequenz · Expansion · Licht',
    yinSeq:'Yin-Sequenz · Kontraktion · Schatten',sacredPairs:'Die heiligen Paare',
    never369:'3, 6 und 9 erscheinen nie in Verdopplungssequenzen.',
    chineseTrad:'Chinesische Tradition',vortexTesla:'Vortex-Mathematik · Tesla',modernPhysics:'Moderne Physik',
    concrete:'Konkrete Manifestationen',kirlian:'Der Kirlian-Effekt',axisCosmic:'Kosmische Achse',fluxYang:'Yang-Fluss',
    cancel:'Abbrechen',save:'Speichern',profile:'Profil',solfeggioSeries:'Solfeggio-Reihe',freqActive:'Aktive Frequenz',
    anchorEarth:'Mit der Erde verankern',subtitle:'Die Geheime Energie des Universums',
    teslaQuote:'"Wenn du die Geheimnisse des Universums finden willst, denke in Begriffen wie Energie, Frequenz und Vibration." — Nikola Tesla',
    ruleOf9Desc: "Jedes Vielfache von 9 lässt sich immer auf 9 reduzieren. Die ewige Konstante.",
    never369Desc: "Sie existieren auf einer eigenen Achse — der kosmischen Achse. Ihre Summe in Paaren ergibt immer 9.",
    yyQuote: '"Im Laufe des Tages hat der Berg immer eine Seite im Schatten und eine im Licht."',
    ewAuthor: "Maxence Layet — Die Geheime Energie des Universums",
    ewIntro: "Tesla erfindet alte östliche Prinzipien durch die Linse des modernen Elektromagnetismus neu.",
    kirlianDesc: "Die <em>Kirlian-Fotografie</em> offenbart das Schwingungsfeld von Lebewesen. Tesla sprach von <strong>Strahlungsenergie</strong>.",
    ewItems: [
      ['Qi (universelle Lebensenergie)','Akupunktur-Meridiane','Yin · Yang (zyklische Dualität)','Feng Shui (geomantische Flüsse)','Qi Gong (Atembeherrschung)','Gedächtnis des Wassers','3 · 6 · 9 (heilige Zahlen)','Das Tao — der universelle Weg'],
      ['Sequenz 1-2-4-8-7-5 + Achse 3-6-9','Toroidales Feld','Yang / Yin Fluss','Kohärenzzonen','Quersumme','Selbstähnlichkeit der 9','Kosmische Achse 3-6-9','Unendlichkeit (∞) im Zentrum'],
      ['Biologisches elektromagnetisches Feld','Elektrodermale Leitfähigkeit','Welle-Teilchen-Dualismus','Quantenkohärenz','Biofeedback · Neurofeedback','Gedächtnis des Wassers','Therapeutische Frequenzen (Hz)','Princeton Global Consciousness Project'],
      ['Rotlichttherapie (660nm→3)','Magnetfeldtherapie','Elektropunktur','Gammabögen der Tibetischen Mönche','Kirlian-Fotografie','Elektrokultur','Gehirn-Computer-Schnittstelle','Schumann 7,83Hz→18→9']
    ],
    resKbd: 'Tastatur: 1–9 · Leertaste: Puls · R: Reset',
    share: 'Teilen',
    digit9: '⟲ 9',
    digitAxis: '◈ Achse',
    digitFlux: '● Fluss',
    ttLang: "Sprache ändern",
    ttProfile: "Profil bearbeiten",
    ttVortexCanvas: "Klicke auf einen Knoten",
    ttAnimate: "Flussanimation umschalten",
    ttTri: "3-6-9 Achse umschalten",
    ttAmber: "1-4-7 Dreieck umschalten",
    ttIndigo: "2-5-8 Dreieck umschalten",
    ttPath: "Yin-Yang-Fluss umschalten",
    ttShare: "Vortexbild teilen",
    ttReduce: "Quersumme berechnen",
    ttNumInput: "Zahl eingeben",
    ttMult: "Vielfache berechnen",
    ttFreqTab: "Frequenz auswählen",
    ttPlayPause: "Abspielen / Pause",
    ttVol: "Lautstärke anpassen",
    ttLoop: "Schleife umschalten",
    ttTimer: "Timer starten",
    ttResCanvas: "Knoten klicken zum Aktivieren",
    ttReset: "Resonanz zurücksetzen",
    ttFolDd: "Frequenz auswählen",
    ttFol369: "369-Achsen umschalten",
    ttFolInfo: "Info umschalten",
    ttFolWave: "Wellenform ändern",
    resIntro: "Ballanciere 3 und 6 aus, um dann mit der 9 die Resonanz zu erhöhen. Die Stabilität sinkt mit asymmetrischer Energie.",
    tuningForkVideo: "Stimmgabel-Video",
    folHowToTitle: "Bedienung des Frequenzgebers",
    folHowToContent: "Berühren oder ziehen Sie im Inneren, um die Resonanz zu modulieren. Die Mitte gibt die reine Frequenz ab.",
    tuningFork: "Stimmgabel",
    tapToPlay: "Tippen zum Abspielen"
  },
  it: {
    nodes: NODES_EN,
    freqs: FREQS_EN,
    folFreqs: FOL_FREQS_EN,
    tabs:['Vortice','Riduzione','Yin · Yang','Frequenze','Ponte Est-Ovest','Risonanza','Fiore della Vita'],
    username:'Nome viaggiatore',login:'Accedi',guest:'Continua come ospite',duelMode:'Modalità duello (IA)',
    animateFlow:'Anima flusso',pauseFlow:'Pausar flusso',selectNode:'Seleziona un numero',
    cosmicRole:'Ruolo cosmico',frequency:'Frequenza',resonance:'Risonanza',stability:'Stabilità',
    leftPolarity:'Polarità sinistra',rightPolarity:'Polarità destra',balance:'Bilancia 6 e 3',
    raiseEnergy:'Eleva l\'energia a 9',gateOpen:'LA PORTA SI APRE',victory:'Vittoria',
    defeat:'Sconfitta',draw:'Pareggio',player:'Giocatore',opponent:'Avversario IA',reset:'Ripristina',
    loop:'Ripeti',session:'Sessione',min:'min',fileMissing:'File mancante:',
    benefits:'Benefici',gates:'Porte pratiche',primary:'Frequenza principale',
    complementary:'Frequenza complementare',tryNumber:'Prova un numero',reduce:'Riduci',
    ruleOf9:'La regola del 9',multiples:'Tabella dei multipli',result:'Risultato',digitSum:'Somma cifre',
    reduced:'Ridotto',pattern:'Pattern',yangSeq:'Sequenza Yang · Espansione · Luce',
    yinSeq:'Sequenza Yin · Contrazione · Ombra',sacredPairs:'Le coppie sacre',
    never369:'3, 6 e 9 non compaiono mai nelle sequenze di raddoppio.',
    chineseTrad:'Tradizione cinese',vortexTesla:'Matematica Vortice · Tesla',modernPhysics:'Fisica moderna',
    concrete:'Manifestazioni concrete',kirlian:'L\'effetto Kirlian',axisCosmic:'Asse cosmico',fluxYang:'Flusso Yang',
    cancel:'Annulla',save:'Salva',profile:'Profilo',solfeggioSeries:'Serie Solfeggio',freqActive:'Frequenza Attiva',
    anchorEarth:'Ancoraggio alla Terra',subtitle:'L\'Energia Segreta dell\'Universo',
    teslaQuote:'"Se vuoi scoprire i segreti dell\'universo, pensa in termini di energia, frequenza e vibrazione." — Nikola Tesla',
    ruleOf9Desc: "Ogni multiplo di 9 si riduce sempre a 9. La costante eterna.",
    never369Desc: "Esistono su un asse separato: l'asse cosmico. La loro somma in coppie dà sempre 9.",
    yyQuote: '"Durante il giorno, la montagna ha sempre un lato in ombra e un altro baciato dalla luce."',
    ewAuthor: "Maxence Layet — L'Energia Segreta dell'Universo",
    ewIntro: "Tesla reinventa antichi principi orientali attraverso la lente dell'elettromagnetismo moderno.",
    kirlianDesc: "La <em>fotografia Kirlian</em> rivela il campo vibratorio degli esseri viventi. Tesla parlava di <strong>Energia Radiante</strong>.",
    ewItems: [
      ['Qi (energia vitale universale)','Meridiani di agopuntura','Yin · Yang (dualità ciclica)','Feng Shui (flussi geomantici)','Qi Gong','Memoria dell\'acqua','3 · 6 · 9 (numeri sacri)','Il Tao'],
      ['Sequenza 1-2-4-8-7-5 + asse 3-6-9','Campo toroidale','Flusso Yang / Yin','Zone di coerenza','Radice numerica','Autosimilarità del 9','Asse cosmico 3-6-9','Infinito (∞) al centro'],
      ['Campo elettromagnetico biologico','Conduttività elettrodermica','Dualità onda/particella','Coerenza quantistica','Biofeedback','Memoria dell\'acqua','Frequenze terapeutiche (Hz)','Princeton Global Consciousness Project'],
      ['Terapia a luce rossa (660nm→3)','Magnetoterapia','Elettropuntura','Onde gamma dei monaci tibetani','Fotografia Kirlian','Elettrocoltura','Interfaccia cervello-computer','Schumann 7.83Hz→18→9']
    ],
    resKbd: 'Tastiera: 1–9 · Spazio: pulsazione · R: reset',
    share: 'Condividi',
    digit9: '⟲ 9',
    digitAxis: '◈ asse',
    digitFlux: '● flusso',
    ttLang: "Cambia lingua",
    ttProfile: "Modifica profilo",
    ttVortexCanvas: "Fai clic su un nodo",
    ttAnimate: "Attiva/disattiva flusso",
    ttTri: "Attiva/disattiva asse 3-6-9",
    ttAmber: "Attiva/disattiva triangolo 1-4-7",
    ttIndigo: "Attiva/disattiva triangolo 2-5-8",
    ttPath: "Attiva/disattiva flusso Yin-Yang",
    ttShare: "Condividi immagine",
    ttReduce: "Calcola somma",
    ttNumInput: "Inserisci numero",
    ttMult: "Calcola multipli",
    ttFreqTab: "Seleziona frequenza",
    ttPlayPause: "Riproduci / Pausa",
    ttVol: "Regola volume",
    ttLoop: "Attiva/disattiva ripetizione",
    ttTimer: "Avvia timer",
    ttResCanvas: "Fai clic per attivare",
    ttReset: "Ripristina risonanza",
    ttFolDd: "Seleziona frequenza",
    ttFol369: "Attiva/disattiva assi 369",
    ttFolInfo: "Attiva/disattiva info",
    ttFolWave: "Cambia forma d'onda",
    resIntro: "Bilancia 3 e 6 del vortice. Usa il 9 per elevare la risonanza fino ad aprire la porta. La stabilità si degrada con il tempo.",
    tuningForkVideo: "Video diapason",
    folHowToTitle: "Come usare il Sequenziatore",
    folHowToContent: "Tocca o trascina per modulare la risonanza. Il centro emette la frequenza pura.",
    tuningFork: "Diapason",
    tapToPlay: "Tocca per riprodurre"
  },
  pt: {
    nodes: NODES_EN,
    freqs: FREQS_EN,
    folFreqs: FOL_FREQS_EN,
    tabs:['Vórtice','Redução','Yin · Yang','Frequências','Ponte Leste-Oeste','Ressonância','Flor da Vida'],
    username:'Nome do viajante',login:'Entrar',guest:'Continuar como convidado',duelMode:'Modo duelo (IA)',
    animateFlow:'Animar fluxo',pauseFlow:'Pausar fluxo',selectNode:'Selecione um número',
    cosmicRole:'Papel cósmico',frequency:'Frequência',resonance:'Ressonância',stability:'Estabilidade',
    leftPolarity:'Polaridade esq.',rightPolarity:'Polaridade dir.',balance:'Equilibre 6 e 3',
    raiseEnergy:'Eleve a energia para 9',gateOpen:'O PORTAL SE ABRE',victory:'Vitória',
    defeat:'Derrota',draw:'Empate',player:'Jogador',opponent:'Adversário IA',reset:'Reiniciar',
    loop:'Repetir',session:'Sessão',min:'min',fileMissing:'Arquivo ausente:',
    benefits:'Benefícios',gates:'Portais práticos',primary:'Frequência principal',
    complementary:'Frequência complementar',tryNumber:'Tente um número',reduce:'Reduzir',
    ruleOf9:'A regra do 9',multiples:'Tabela de múltiplos',result:'Resultado',digitSum:'Soma digital',
    reduced:'Reduzido',pattern:'Padrão',yangSeq:'Sequência Yang · Expansão · Luz',
    yinSeq:'Sequência Yin · Contração · Sombra',sacredPairs:'Os pares sagrados',
    never369:'3, 6 e 9 nunca aparecem nas sequências de duplicação.',
    chineseTrad:'Tradição chinesa',vortexTesla:'Matemática Vórtice · Tesla',modernPhysics:'Física moderna',
    concrete:'Manifestações concretas',kirlian:'O efeito Kirlian',axisCosmic:'Eixo cósmico',fluxYang:'Fluxo Yang',
    cancel:'Cancelar',save:'Salvar',profile:'Perfil',solfeggioSeries:'Série Solfeggio',freqActive:'Frequência Ativa',
    anchorEarth:'Ancorar com a Terra',subtitle:'A Energia Secreta do Universo',
    teslaQuote:'"Se você quer encontrar os segredos do universo, pense em termos de energia, frequência e vibração." — Nikola Tesla',
    ruleOf9Desc: "Cada múltiplo de 9 é sempre reduzido a 9. A constante eterna.",
    never369Desc: "Eles existem num eixo separado: o eixo cósmico. A soma deles em pares resulta sempre em 9.",
    yyQuote: '"Ao longo do dia, a montanha tem sempre um lado na sombra e outro banhado de luz."',
    ewAuthor: "Maxence Layet — A Energia Secreta do Universo",
    ewIntro: "Tesla reinventa antigos princípios orientais pelas lentes do eletromagnetismo moderno.",
    kirlianDesc: "A <em>fotografia Kirlian</em> revela o campo vibratório. Tesla falou de <strong>Energia Radiante</strong>.",
    ewItems: [
      ['Qi (energia energética universal)','Meridianos de acupuntura','Yin · Yang (dualidade)','Feng Shui (fluxos)','Qi Gong','Memória da água','3 · 6 · 9 (números sagrados)','O Tao'],
      ['Sequência 1-2-4-8-7-5 + eixo 3-6-9','Campo toroidal','Fluxo Yang / Yin','Zonas de coerência','Soma de dígitos','Autossimilaridade do 9','Eixo cósmico 3-6-9','Infinito (∞) no centro'],
      ['Campo eletromagnético','Condutividade eletrodérmica','Dualidade onda/partícula','Coerência quântica','Biofeedback','Memória da água','Frequências terapêuticas','Projeto Consciência Global Princeton'],
      ['Terapia de luz vermelha (660nm→3)','Magnetoterapia','Eletropuntura','Ondas gama monges tibetanos','Fotografia Kirlian','Eletrocultura','Interface cérebro-computador','Schumann 7.83Hz→18→9']
    ],
    resKbd: 'Teclado: 1–9 · Espaço: pulsação · R: resetar',
    share: 'Compartilhar',
    digit9: '⟲ 9',
    digitAxis: '◈ eixo',
    digitFlux: '● fluxo',
    ttLang: "Mudar idioma",
    ttProfile: "Editar perfil",
    ttVortexCanvas: "Clique num nó",
    ttAnimate: "Alternar fluxo",
    ttTri: "Alternar eixo 3-6-9",
    ttAmber: "Alternar 1-4-7",
    ttIndigo: "Alternar 2-5-8",
    ttPath: "Alternar Yin-Yang",
    ttShare: "Compartilhar imagem",
    ttReduce: "Calcular soma",
    ttNumInput: "Inserir número",
    ttMult: "Calcular múltiplos",
    ttFreqTab: "Selecionar frequência",
    ttPlayPause: "Tocar / Pausar",
    ttVol: "Ajustar volume",
    ttLoop: "Alternar loop",
    ttTimer: "Iniciar cronômetro",
    ttResCanvas: "Clique para ativar",
    ttReset: "Resetar ressonância",
    ttFolDd: "Selecionar frequência",
    ttFol369: "Alternar eixos 369",
    ttFolInfo: "Alternar info",
    ttFolWave: "Mudar forma de onda",
    resIntro: "Equilibre 3 e 6 do vórtice. Use o 9 para elevar a ressonância até abrir a porta. A estabilidade cai com assimetria.",
    tuningForkVideo: "Vídeo diapasão",
    folHowToTitle: "Como usar o Frequenciador",
    folHowToContent: "Toque ou arraste para modular a ressonância. O centro emite a frequência pura.",
    tuningFork: "Diapasão",
    tapToPlay: "Toque para ouvir"
  }
};
